//! src/lib.rs
//!
//! @description
//! This is the main entry point for the Aces Unknown on-chain program.
//! It defines the program's instructions, state accounts, and custom errors.
//! The program orchestrates the public aspects of the poker game on Solana,
//! such as managing tables and player actions, while delegating all confidential
//! logic (card shuffling, dealing, showdowns) to the Arcium network.
//!
//! The program is built using the Anchor framework for Solana and the Arcis
//! framework for confidential computations on Arcium.

use anchor_lang::prelude::*;
use arcium_anchor::prelude::*;
use anchor_spl::token::{self, Token, TokenAccount};

// Import local modules.
pub mod state;
pub mod error;
pub mod instructions;

// Make their contents available for the program.
use state::*;
use instructions::*;
use error::AcesUnknownErrorCode;
use anchor_spl::token::Transfer;

// Callback structs are handled by the #[arcium_callback] macros

// Arcium Encrypted Data Types (these will be generated by macros)

// Arcium Computation Definition Offsets
// These constants are unique identifiers for each confidential instruction.
const COMP_DEF_OFFSET_SHUFFLE_AND_DEAL: u32 = comp_def_offset("shuffle_and_deal");
const COMP_DEF_OFFSET_REVEAL_COMMUNITY_CARDS: u32 = comp_def_offset("reveal_community_cards");
const COMP_DEF_OFFSET_EVALUATE_HANDS_AND_PAYOUT: u32 = comp_def_offset("evaluate_hands_and_payout");

// Program ID
declare_id!("8U3ombZzPCggjjz26FRZ2kjhvtFWWRXv9Zrn6vuNvJj2");

#[arcium_program]
pub mod aces_unknown {
    use super::*;

    // ========================================
    // Admin & Table Management Instructions
    // ========================================

    /// Initializes a `PlatformConfig` singleton account with the deployer as the admin.
    /// This should be called once after the program is deployed.
    pub fn initialize_platform_config(ctx: Context<InitializePlatformConfig>) -> Result<()> {
        ctx.accounts.platform_config.admin = ctx.accounts.admin.key();
        ctx.accounts.platform_config.rake_bps = 500; // Default 5.00%
        ctx.accounts.platform_config.rake_max_cap = 0; // Default no cap
        ctx.accounts.platform_config.treasury_vault = ctx.accounts.treasury_vault.key();
        Ok(())
    }

    /// Instruction for the platform admin to update rake parameters.
    pub fn update_rake_params(
        ctx: Context<UpdateRakeParams>,
        new_rake_bps: u16,
        new_rake_max_cap: u64,
    ) -> Result<()> {
        instructions::update_rake_params::update_rake_params(ctx, new_rake_bps, new_rake_max_cap)
    }

    /// Instruction for a player to create a new poker table.
    pub fn create_table(
        ctx: Context<CreateTable>,
        table_id: u64,
        small_blind: u64,
        big_blind: u64,
        buy_in: u64,
    ) -> Result<()> {
        instructions::create_table::create_table(ctx, table_id, small_blind, big_blind, buy_in)
    }

    /// Instruction for a player to join an existing table.
    pub fn join_table(ctx: Context<JoinTable>, table_id: u64, seat_index: u8, buy_in: u64) -> Result<()> {
        instructions::join_table::join_table(ctx, table_id, seat_index, buy_in)
    }

    /// Instruction for a player to leave a table and cash out their chips.
    pub fn leave_table(ctx: Context<LeaveTable>, table_id: u64) -> Result<()> {
        instructions::leave_table::leave_table(ctx, table_id)
    }

    // ========================================
    // Hand Lifecycle Instructions
    // ========================================

    /// Starts a new hand, collects blinds, and queues the shuffle/deal computation.
    pub fn start_hand(ctx: Context<StartHand>, table_id: u64) -> Result<()> {
        instructions::start_hand::start_hand(ctx, table_id)
    }

    /// Reveals the next community cards (flop, turn, or river).
    pub fn deal_community_cards(ctx: Context<DealCommunityCards>, table_id: u64) -> Result<()> {
        instructions::deal_community_cards::deal_community_cards(ctx, table_id)
    }

    /// Resolves the showdown, determines the winner, and handles payouts.
    pub fn resolve_showdown(ctx: Context<ResolveShowdown>, table_id: u64) -> Result<()> {
        instructions::resolve_showdown::resolve_showdown(ctx, table_id)
    }
    
    // ========================================
    // Player Action & Timeout Instructions
    // ========================================
    
    /// The main instruction for a player to take an action (fold, check, call, bet, raise).
    pub fn player_action(ctx: Context<PlayerActionAccounts>, table_id: u64, action: crate::state::PlayerAction) -> Result<()> {
        instructions::player_action::player_action(ctx, table_id, action)
    }

    /// Instruction for anyone to fold a player whose turn timer has expired.
    pub fn force_player_fold(ctx: Context<ForcePlayerFold>, table_id: u64) -> Result<()> {
        instructions::force_player_fold::force_player_fold(ctx, table_id)
    }

    /// Safety instruction to refund all bets if a hand becomes unrecoverably stuck.
    pub fn force_hand_refund(ctx: Context<ForceHandRefund>, table_id: u64) -> Result<()> {
        instructions::force_hand_refund::force_hand_refund(ctx, table_id)
    }

    // ========================================
    // Arcium Callbacks (placeholders - to be implemented when Arcium integration is properly set up)
    // ========================================
}



/// Context for initializing the `PlatformConfig` account.
#[derive(Accounts)]
pub struct InitializePlatformConfig<'info> {
    #[account(
        init,
        payer = admin,
        space = 8 + PlatformConfig::INIT_SPACE,
        seeds = [b"platform_config"],
        bump
    )]
    pub platform_config: Account<'info, PlatformConfig>,
    #[account(mut)]
    pub admin: Signer<'info>,
    /// CHECK: Treasury vault account for platform rake collection
    pub treasury_vault: UncheckedAccount<'info>,
    pub system_program: Program<'info, System>,
}

// ========================================
// Callback Account Structs (generated by macros)
// ========================================
